spring:
  application:
    name: spring_demo
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis?autoReconnect=true&failOverReadOnly=false&autoReconnectForPools=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: Sakuya520!
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8080